### PR TITLE
Test the library and update dependencies

### PR DESCRIPTION
**Pull request by doomhz**
Added tests and updated the syntax while keeping the same API.

### CODE REVIEW

**Comment by fereidani** [comment]
Hi Dumitru (@doomhz),
Thank you for your pull request , neat job .
I think due compatibility reasons removing bluebird is a bad idea .

**Comment by doomhz** [comment]
Thanks @fereidani!
I think that the native promises shouldn't be a problem since they are supported in all the node versions above 0.10 (http://node.green/#Promise). Might be interesting to just release a new version of recaptcha2 and the users that still run on node 0.10 can stay in the old version. What do you think?

**Comment by fereidani** [comment]
sounds good ,
it will be better to use version 1.1.0 instead since removing bluebird is a major change .
as node v0.10 reach its end of life on October 31 , it's no longer required to support it  .

**Comment by doomhz** [comment]
v 1.1 seems to be the best solution. The new code can be merged on master and and pushed to npm. Older projects will have to use the previous version. Maybe also have 2 releases on GitHub listing the changelog?

**Comment by fereidani** [comment]
yes v1.1.0 is good solution ,
also a CHANGELOG.md file is a good idea .
but i think 2 branches is not necessary since we drop support for node 0.10 .
please add new commits , to start merge process .

**Comment by doomhz** [comment]
added the changelog file, are we missing something else?

**Comment by doomhz** [comment]
it might be interesting to add a TravisCI tag after branch merging

**Comment by fereidani** [comment]
Thanks , it seems you forget to change version in package.json .
TravisCI is very good idea . but lets merge first .

**Comment by doomhz** [comment]
ah, yes, indeed, it's changed now.

**Comment by doomhz** [comment]
Can you release a new version on npm?

**Comment by fereidani** [comment]
it's already on npm as version of 1.3.2 .
i had some versioning trouble due mistake and publish of 1.3 instead of 1.1 .
and unfortunately npm unpublish does not work very well .

**Pull request merged**
